### ISSUE TITLE
Does not seem to work in WebStorm

### ISSUE THREAD

**Issue by Dan1ve** [serkangunes/ClosurePlugin#8]
Having this plugin would be absolutely amazing, but it seems that it's not working in WebStorm (2018).

The plugin installed just fine, but I don't receive any warnings for missing goog.requires. Are there any additional steps I need to take?

**Comment by serkangunes** [comment]
I haven't updated the plugin for a while which version of WebStorm are you using?

**Comment by serkangunes** [comment]
I haven't updated the plugin for a while. I will double check whether it works in new version of WebStorm.

**Comment by serkangunes** [comment]
Updated the plugin and published new version should work now.

**Comment by Dan1ve** [comment]
Thanks, I appreciate your fast response!
However, the plugin does still not work, because the PsiFactory is only available for the Java IDE. I'll look into this!

**Comment by serkangunes** [comment]
Ok sorry about that. I should have restricted to only to IntelliJ apologies.

**Comment by Dan1ve** [comment]
No worries! This project inspired me to create a new plugin, see https://github.com/Dan1ve/ClosureInspectionsPlugin  
Thanks for your work on this.
